### ISSUE TITLE
Don't use slashes as path separator!

### ISSUE THREAD

**Issue by MikuAuahDark** [neomantra/lds#2]
This only _accidentally_ works under some platforms. Use dots (`.`) as path separator for maximum compatibility instead!

https://github.com/neomantra/lds/blob/80f316661aa282f62e0abf6790f9f8615e2b7473/lds.lua#L10-L15
https://github.com/neomantra/lds/blob/80f316661aa282f62e0abf6790f9f8615e2b7473/lds/Array.lua#L20
https://github.com/neomantra/lds/blob/80f316661aa282f62e0abf6790f9f8615e2b7473/lds/HashMap.lua#L26-L27
https://github.com/neomantra/lds/blob/80f316661aa282f62e0abf6790f9f8615e2b7473/lds/Vector.lua#L20
https://github.com/neomantra/lds/blob/80f316661aa282f62e0abf6790f9f8615e2b7473/lds/allocator.lua#L22
https://github.com/neomantra/lds/blob/80f316661aa282f62e0abf6790f9f8615e2b7473/lds/hash.lua#L11

**Comment by neomantra** [comment]
Thanks for the report!    I'll fix it now -- pretty straight forward.

Do you know if the rockspec file works with the slashes in the install directory?

**Comment by MikuAuahDark** [comment]
No idea for rockspec files, since I never tried to make one. Sorry.

**Comment by zorggn** [comment]
From what i skimmed from the following page, i think the install dir. stuff in your rockspec file should be fine syntax-wise. https://github.com/luarocks/luarocks/wiki/Rockspec-format#build-rules

**Comment by neomantra** [comment]
Cool, thanks for the reports.   I updated that.  Also added Travis testing and git tags.
